name: Complete Release and Deploy

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to deploy (e.g. v1.0.0)'
        required: false
      rel:
        description: 'Release number (e.g. 1)'
        required: false
        default: '1'
      prerelease:
        description: 'Mark as prerelease'
        required: false
        type: boolean
        default: false

jobs:
  release_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Optional: Install dependencies, run tests, etc.
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y zip

      - name: Build and Prepare Release
        id: release
        uses: Da4ndo/rust-aur-release-deploy@v2
        with:
          # Required parameters
          package_name: your-package-name
          
          # Version control
          version: ${{ github.event.inputs.version }}
          rel: ${{ github.event.inputs.rel || '1' }}
          prerelease: ${{ github.event.inputs.prerelease }}
          
          # Build configuration
          platform: both  # 'linux', 'windows', or 'both'
          
          # Additional files to include
          linux_files: '["LICENSE", "README.md", "config.toml"]'
          windows_files: '["LICENSE", "README.md", "config.win.toml"]'
          release_files: '["CHANGELOG.md", "docs/*"]'
          
          # AUR configuration
          prepare_aur: true
          pkgbuild: './PKGBUILD'
          pkgbuild_output_path: './prepared_pkgbuild/PKGBUILD'
          
          # Release configuration
          auto_release: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Optional: Create release notes
      - name: Generate Release Notes
        if: success()
        run: |
          echo "## Release Information" > release_notes.md
          echo "### Linux Build" >> release_notes.md
          if [[ -n "${{ steps.release.outputs.linux_archive }}" ]]; then
            echo "- Archive: ${{ steps.release.outputs.linux_archive }}" >> release_notes.md
            echo "- SHA256: ${{ steps.release.outputs.linux_sha256 }}" >> release_notes.md
          fi
          echo "### Windows Build" >> release_notes.md
          if [[ -n "${{ steps.release.outputs.windows_archive }}" ]]; then
            echo "- Archive: ${{ steps.release.outputs.windows_archive }}" >> release_notes.md
            echo "- SHA256: ${{ steps.release.outputs.windows_sha256 }}" >> release_notes.md
          fi

      - name: Deploy to AUR
        uses: KSXGitHub/github-actions-deploy-aur@v4.1.1
        with:
          pkgname: your-package-name
          pkgbuild: ${{ steps.release.outputs.pkgbuild_path }}
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: "Update to version ${{ steps.release.outputs.version }}"
          ssh_keyscan_types: rsa,ecdsa,ed25519

      # Optional: Update documentation
      - name: Update Documentation
        if: success()
        run: |
          echo "## Installation" > INSTALL.md
          echo "### From AUR (Arch Linux)" >> INSTALL.md
          echo "\`\`\`bash" >> INSTALL.md
          echo "yay -S your-package-name" >> INSTALL.md
          echo "\`\`\`" >> INSTALL.md
          echo "### Manual Installation" >> INSTALL.md
          echo "Download the appropriate package for your system:" >> INSTALL.md
          if [[ -n "${{ steps.release.outputs.linux_archive }}" ]]; then
            echo "- Linux: [your-package-name-${{ steps.release.outputs.version }}-linux-x86_64.tar.gz](${{ steps.release.outputs.linux_archive }})" >> INSTALL.md
          fi
          if [[ -n "${{ steps.release.outputs.windows_archive }}" ]]; then
            echo "- Windows: [your-package-name-${{ steps.release.outputs.version }}-windows-x86_64.zip](${{ steps.release.outputs.windows_archive }})" >> INSTALL.md
          fi 